
name renameFile


on:
  push:
    branches: 
      - main
  workflow_dispatch:


permissions:
 
  contents: write 

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: go_path              
        run: |
          echo cd src/main/java
    
